task:
  name: Gradle Tests
  container:
    image: gradle:jdk11
    cpu: 4
    memory: 16G
  gradle_cache:
    folder: ~/.gradle/caches
    reupload_on_changes: true
  check_script: gradle check

task:
  name: Bazel Tests
  container:
    image: l.gcr.io/google/bazel:latest
    cpu: 4
    memory: 16G
  test_script: bazel test --remote_cache=http://$CIRRUS_HTTP_CACHE_HOST //services/...
