name: Tests
on:
  push:
  pull_request:

jobs:
  test-remote:
    runs-on: ubuntu-latest
    name: Bazel (Remote Caching)
    steps:
      - uses: actions/checkout@v2
      - uses: cirruslabs/http-cache-action@master
      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 3.5.0
      - run: bazel version
      - run: bazel test --remote_http_cache=http://localhost:12321 //services/...
      - name: debug info
        run: |
          docker ps
          docker logs cache_proxy
  test-local:
    runs-on: ubuntu-latest
    name: Bazel (No Caching)
    steps:
      - uses: actions/checkout@v2
      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 3.5.0
      - run: bazel version
      - run: bazel test //services/...
